### PR TITLE
Add ordinal_format()

### PR DESCRIPTION
**Pull request by aaronwolen**
I often use this snippet in reports to include sentences like

> GeneX is the 2nd most significant result.

using

```
`r gene` is the `r ordinal(which(gene == genes))` most significant result.
```

and thought it might be a useful addition to scales.

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind adding a few unit tests? e.g. for 1, 11, 21

**Comment by aaronwolen** [comment]
Sure, just added the tests and rebased. However, I see Travis docked a few points for using NSE with `arrange()`. I'll fix that.

**Comment by aaronwolen** [comment]
Okay, should be ready to go!

**Comment by hadley** [comment]
And a bullet point in NEWS please?

**Comment by aaronwolen** [comment]
Done :thumbsup:

**Pull request merged**
