### PR TITLE
add bullet to NEWS for #51

### PR DESCRIPTION
**Pull request by dvmlls**

### CODE REVIEW

**Comment by hadley** [comment]
Is there a reason you did this in a separate PR?

**Comment by dvmlls** [comment]
Ya I wasn't sure how to do that, but I'll figure it out!

**Comment by hadley** [comment]
You managed to do it for the formatting change ;)

**Comment by dvmlls** [comment]
Dumb luck.

Is this better? https://github.com/hadley/scales/pull/51/files

**Pull request closed without merging**
